#! /bin/sh
set -u

package="$1"

for cmdname in $([ -f $package/PKG/uses-commands ] && cat $package/PKG/uses-commands | sort -u)
do
    if ! command -v $cmdname 2>&1 >/dev/null; then
        echo $cmdname
    fi
done
