
if !exists('$XDG_CONFIG_HOME')
	let $XDG_CONFIG_HOME = $HOME . '/.config'
endif

if !exists('$XDG_DATA_HOME')
	let $XDG_DATA_HOME = $HOME . '/.local/share'
endif

if !exists('$XDG_CACHE_HOME')
	let $XDG_CACHE_HOME = $HOME . '/.cache'
endif

let $VIM_CONFIG_HOME = $XDG_CONFIG_HOME . '/vim'
let $VIM_DATA_HOME = $XDG_DATA_HOME . '/vim'
let $VIM_CACHE_HOME = $XDG_CACHE_HOME . '/vim'

if empty( glob($VIM_CONFIG_HOME) )
	call mkdir($VIM_CONFIG_HOME, 'p')
endif

if empty( glob($VIM_DATA_HOME) )
	call mkdir($VIM_DATA_HOME, 'p')
endif

if empty( glob($VIM_CACHE_HOME) )
	call mkdir($VIM_CACHE_HOME, 'p')
endif

let $MYVIMRC = $VIM_CONFIG_HOME . '/vimrc'

set runtimepath=$VIM_CONFIG_HOME,$VIM,$VIMRUNTIME
runtime! init/*.vim

